dicom: add and update requirements
```
Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/imgteam/highdicom_dicom2tiff/d91c748f7114/highdicom_dicom2tiff/dicom2tiff.py", line 171, in <module>
    dicom_to_tiff(
    ~~~~~~~~~~~~~^
        args.dcm,
        ^^^^^^^^^
    ...<6 lines>...
        ),
        ^^
    )
    ^
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/imgteam/highdicom_dicom2tiff/d91c748f7114/highdicom_dicom2tiff/dicom2tiff.py", line 57, in dicom_to_tiff
    arr = dcm.get_volume(**config).array
          ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/highdicom/image.py", line 6733, in get_volume
    array = self._get_pixels_by_frame(
        spatial_shape=volume_geometry.spatial_shape[0],
    ...<10 lines>...
        dtype=dtype,
    )
  File "/usr/local/lib/python3.13/site-packages/highdicom/image.py", line 5195, in _get_pixels_by_frame
    frame = frame_transform(frame_bytes, frame_index)
  File "/usr/local/lib/python3.13/site-packages/highdicom/image.py", line 1000, in __call__
    frame_out = decode_frame(
        value=frame,
    ...<9 lines>...
        index=frame_index,
    )
  File "/usr/local/lib/python3.13/site-packages/highdicom/frame.py", line 473, in decode_frame
    array, _ = decoder.as_array(
               ~~~~~~~~~~~~~~~~^
        src=value,
        ^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pydicom/pixels/decoders/base.py", line 982, in as_array
    self._validate_plugins(decoding_plugin),
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pydicom/pixels/common.py", line 257, in _validate_plugins
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: Unable to decompress 'JPEG Lossless, Non-Hierarchical (Process 14)' pixel data because all plugins are missing dependencies:
	gdcm - requires gdcm>=3.0.10
	pylibjpeg - requires pylibjpeg>=2.0 and pylibjpeg-libjpeg>=2.1
```

updating giatools to the latest version raised another exception. so I
left it.